version: '3'

services:
    web:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes: 
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
        networks:
            - mysql-compose-network
    php:
        build: .
        container_name: php-fpm
        volumes:
            - ./www:/www
        links:
            - db
        networks:
            - mysql-compose-network
    db:
        image: mysql:5.7
        container_name: mysql
        expose:
            - "3306"
        volumes:
            - ./db:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: teste
            MYSQL_HOST: mysql
        networks:
            - mysql-compose-network
    adminer:
        image: adminer
        restart: always
        ports:
            - 5000:8080
        networks:
            - mysql-compose-network

networks: 
    mysql-compose-network:
        driver: bridge